### ISSUE TITLE
GitHub Actions publish workflow is broken

### ISSUE THREAD

**Issue by jasongitmail** [parzh/iso4217#17]
Very useful package! Thanks for creating this.

> All the data is guaranteed to be up-to-date at all times:
> the data in the original XML file [is maintained by the Swiss Association for Standardization](https://www.six-group.com/en/products-services/financial-information/data-standards.html#maintenance-agency) (SNV);
> the data in the resulting JSON file [is automatically updated by CI/CD script](https://github.com/parzh/iso4217/blob/28cc291e156b2f648766d7b4fd914d273e985e49/.github/workflows/publish-xml-updates.yml) on a daily basis;

The ReadMe says to expect updates on a daily basis, so it appears something may have broken.

**Comment by parzhitsky** [comment]
Fixed it. Turns out, my bot's PAT had expired. I don't know I could have deduced this from these messages:

<img width="1838" alt="image" src="https://github.com/parzh/iso4217/assets/59528510/88b82121-09c6-4e58-a608-ee0b9b907a9e">

**Comment by jasongitmail** [comment]
Great! Thanks for looking into it
