### ISSUE TITLE
Update library with Croatia's move to the Euro

### ISSUE THREAD

**Issue by tiagoalves** [parzh/iso4217#8]
Thank you so much for this self-updating library. As you may know, Croatia moved to the Euro on January 1st. This has been reflected already in the source XML files but this library hasn't been updated yet.

As far as I understand, the library is updated every Friday so by then this should be fixed. Right?

This can be quite a long tome for such data to be outdated. Do you think it would make sense to update the GitHub workflow to run every day?

**Comment by parzhitsky** [comment]
Thanks for using the package!

> As far as I understand, the library is updated every Friday so by then this should be fixed. Right?

Yes, it is pretty well automated, the data should get updated automatically this Friday. But I've [manually spun the update for you just now, check it out][(https://github.com/parzh/iso4217/actions/runs/3831911530).

> Do you think it would make sense to update the GitHub workflow to run every day?

Not sure every day would be the best option. Perhaps, it would make sense to additionally update the data at the 1st day of every month? This can be done.

**Comment by parzhitsky** [comment]
Seems to have been successfully published, I'm closing the issue.

**Comment by tiagoalves** [comment]
Thank you for the quick update.

About when to run the update workflow, I'm not sure either. On the first day of the month specifically makes sense to me. But I'm worried about timezone differences of a) the country that changes the currency, b) the time at which the ISO standard is updated and c) the time at which this workflow runs. If the workflow runs before a) or b), it won't pick up the updated currency. That's why I think running this once a day should be frequent enough to pick up changes but also not too frequent to be be abusive towards the source file server. But I don't have strong opinions about this :).

**Comment by parzhitsky** [comment]
Well indeed, if it ain’t broke then don’t fix it, right? After all, I’m not a maintainer of GitHub or ISO API, request rate limiting is not my concern. Once a day it is.
